export const refs = {
  sliders: document.querySelectorAll( '.range-slider' ),
  mainForm: document.getElementById('roi-form'),
  mainButtonSubmit: document.querySelector('.roi-form__submit'),
  countrySelect: document.querySelector('[name=country]'),
  industrySelect: document.querySelector('[name=industry]'),
  inputNumberOfEmployees: document.querySelector('[name=NumberOfEmployees]'),
  inputMonthlyEmailVolume: document.querySelector('[name=MonthlyEmailVolume]'),
  threeYearsROIDollars:document.querySelector('.result-query--currency'),
  threeYearsROIPercents:document.querySelector('.result-query--percent'),
  paybackPeriodMonths:document.querySelector('.result-query--months'),
  phishingAttackRatio:  document.querySelector('[name=PhishingAttackRatio]'),
  malwareAttackRation:  document.querySelector('[name=MalwareAttackRatio]'),
  spamRatio:  document.querySelector('[name=SpamAttackRatio]'),
  monthToDeploy:  document.querySelector('[name=MonthsToDeploy]'),
  numberOfSocAnalystsInTheTeam:  document.querySelector('[name=NumberOfSocAnalysts]'),
  socAnalystCostOfSalary:  document.querySelector('[name=SOCSalary]'),
  rangeList: document.querySelector('.range-list'),
  attacksPreventedList: document.querySelector('.attacks-prevented__list'),
  roiMetricsList: document.querySelector('.roi-metrics__list'),
  summaryList: document.querySelector('.summary__list'),
  hbsFormSubmit: document.querySelector('.hbs-form__calculator input[type=submit]'),
  formFullReport: document.querySelector('.full-report'),
  savePDFBtn: document.querySelector('.summary__download')
}